version: 0.2

phases:
  pre_build:
    commands:
        # install npm
        - npm install     
  build:
    commands:
        - npm run build
  post_build:
    commands: 
        -npm start
     
artifacts:
  files:
    -"**/*"
  discard-paths: no
  base-directory: root
  
