version: 0.2

phases:
  per-build:
    commands:
        # install npm
        - npm install     
  build:
    commands:
        - npm run build
     
artifacts:
  files:
    -"**/*"
  discard-paths: no
  base-directory: build
  
